apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "kubeproject"
  namespace: "nodejs"
  labels:
    app: "k8s-node"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "k8s-node"
  template:
    metadata:
      labels:
        app: "k8s-node"
    spec:
      containers:
        - name: "kubeproject"
          image: "642611985562.dkr.ecr.us-east-2.amazonaws.com/project_kubernetes:buildNumber"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
